### PR TITLE
Fix URLs for Curseforge endpoints to get uploads to function

### PR DESCRIPTION
**Pull request by plusmouse**
Not sure if this is needed indefinitely, or if Curseforge will change their endpoints back, but for anyone who wants the new URLs they're in this pull request.

### CODE REVIEW

**Comment by nebularg** [comment]
Thanks! Where did you get the cloudflare.curseforge.com domain? www seems to work as well and was mentioned by the devs in the past so I'm going to use that for now

**Comment by plusmouse** [comment]
The text cloudflare was in the error message as the thing that it had been replaced by

**Comment by nebularg** [comment]
I never saw an error message, what was the full message?

**Comment by p3lim** [comment]
This should be resolved now, according to the head of communities @ Overwolf/CurseForge.

**Pull request closed without merging**
