### PR TITLE
Add GitHub Action (round two)

### PR DESCRIPTION
**Pull request by p3lim**
Alright, so this is a revisit of #44, I've tested that the workflow works now.

1. create a new workflow (e.g. `.github/workflows/release.yml`)
2. configure workflow
	```yaml
	on: push
	jobs:
	  release:
	    runs-on: ubuntu-latest
	    steps:
	      # pull the repository (required)
	      - uses: actions/checkout@v2

	      # run release.sh without any arguments (default), using the game version from TOC
	      - uses: BigWigsMods/packager@github-action

	      # run release.sh with arguments, e.g. targeting Classic
	      - uses: BigWigsMods/packager@github-action
	        with:
	          args: -g 1.13.2 -w 0
	```
3. push anything to see it run

If more people could test this that would be great, once it's in I'll add it to the [marketplace](https://github.com/marketplace?type=actions) and create a wiki page with more scenarios.

Workflow example runs:

- with no args:
   <https://github.com/p3lim/test-action/runs/959848376?check_suite_focus=true>
   ([workflow](https://github.com/p3lim/test-action/actions/runs/199679005/workflow))
- with args targeting classic:
   <https://github.com/p3lim/test-action/runs/959863680?check_suite_focus=true>
   ([workflow](https://github.com/p3lim/test-action/actions/runs/199684248/workflow))

### CODE REVIEW

**Comment by Solor** [comment]
auto increase tag would be handy 😄

**Comment by p3lim** [comment]
@Solor has nothing to do with this PR, and frankly, not really this project.

**Comment by Solor** [comment]
> @Solor has nothing to do with this PR, and frankly, not really this project.

I know, but if you are going to create a automatic wow addon packager for github action, auto tag function would be really useful 👍

**Comment by p3lim** [comment]
Tags is literally what would trigger this action, not the other way around.

**Comment by p3lim** [comment]
Workflow example runs:

- with no args:
   <https://github.com/p3lim/test-action/runs/959848376?check_suite_focus=true>
- with args targeting classic:
   <https://github.com/p3lim/test-action/runs/959863680?check_suite_focus=true>

**Comment by p3lim** [comment]
Actual push using the PR:
https://github.com/p3lim-wow/InteractiveWormholes/runs/960516621?check_suite_focus=true

This was only targeting retail, will test with multi-target too.

**Comment by p3lim** [comment]
Push using the PR against both retail and classic in same workflow:
https://github.com/p3lim-wow/LibProcessable/runs/960562530

Workflow:
https://github.com/p3lim-wow/LibProcessable/actions/runs/199930588/workflow

**Comment by nebularg** [comment]
Thanks!

**Comment by p3lim** [comment]
Wiki is set up: https://github.com/BigWigsMods/packager/wiki/GitHub-Actions---workflow

**Pull request merged**
