### PR TITLE
Preliminary 3.4.0 Support

### PR DESCRIPTION
**Pull request by CDAGaming**
- Evidence in datamining has shown `_Wrath` to be the new suffix, hence it's preliminary implementation.

CF Releases fallback to TBC's Game Type ID, to prevent accidental releases as Retail and since the API is closer based to 9.2.5 and TBC then anything else.

### CODE REVIEW

**Review by Meorawr — COMMENTED** [review]
Nitpick: All your added lines are indented with spaces, whereas the rest of the file uses tabs.

I'm not sure defaulting to the TBC game ID for CF *without the warning message being printed* is a good idea as that could lead to surprises for any addons that aren't multitoc-compatible.

**Comment by Sharparam** [comment]
If CF doesn't support Wrath yet then shouldn't uploading Wrath packages to CF just be disabled until they support it?

**Comment by Meorawr** [comment]
> If CF doesn't support Wrath yet then shouldn't uploading Wrath packages to CF just be disabled until they support it?

For packages that explicitly _only_ support and target Wrath, yes - to me it'd make no sense to upload such a package to a platform that doesn't support that game version.

For multi-client packages that support versions _other_ than Wrath, no - it should just flag it as supporting the other game versions and log a warning stating that the packager was only able to mark compatibility with a subset of the supported game versions.

**Comment by CDAGaming** [comment]
Fixed up the indents and added a clearer message/warning for while CF doesn't support wrath. Presumably, if we just dont want it to upload to CF at all as wrath, then I'd assume the id assignment could just be removed or made invalid. Either way, up to you all 👍

**Comment by nebularg** [comment]
Thanks for doing the work to get this ready 😛 Everything looks fine, but I'll probably sit on this for a bit until we actually get some wrath support/servers

**Comment by CDAGaming** [comment]
Happy to help. At most, the only change thatll be needed to thos after merging is adding the curseforge game type once cf implements it, and possibly adding a few aliases for -Wrath depending on how devs end up packaging releases (In a perfect world, theyd all use -Wrath, but looking at the aliases bcc uses, its unlikely)

**Comment by Meorawr** [comment]
There won't be a need for any TOC suffix aliases; they only exist for Classic Era/TBC because Blizzard changed the original pair of suffixes in a patch after some addons had already started using the older ones.

**Comment by Meorawr** [comment]
Per #126 and some manual digging it seems we got a suffix alias anyway - `WOTLKC`. I guess the packager should support it for the few people who'll be using that suffix for whatever reason.

**Comment by QartemisT** [comment]
There will need to be a fix much like there is `[[ "$wago_type" == "bcc" ]] && wago_type="bc"`, but for wrath -> wotlk, for the Wago support

**Comment by CDAGaming** [comment]
Ill implement both these suggestions either later today or tomorrow morning, depending on time. Thanks for letting me know :)

**Comment by CDAGaming** [comment]
https://www.wowhead.com/wotlk/news/addons-enabled-on-wrath-classic-beta-questie-weakauras-wowhead-looter-327667?webhook

Addon Support for WOTLK is now Live on the Beta, Let the games begin!

**Comment by QartemisT** [comment]
Confirmed tested and working.
:) Amazing PR

**Review by QartemisT — APPROVED** [review]

**Comment by CDAGaming** [comment]
Ah yeah, forgot to comment:

On behalf of commit `bb7e652`, CurseForge uploading should now be fully operational.
Pending any further issues, this PR is officially ready for review/approval 👍

**Comment by nebularg** [comment]
Thank you for your service, sir

**Pull request merged**
